# Generated by Django 5.1.7 on 2025-05-05 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('correo_universitario', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioConductor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentacionConductor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('numero_placas', 'Número de Placas'), ('marca_modelo_año', 'Marca, Modelo y Año del Vehículo'), ('licencia_conducir', 'Licencia de Conducir'), ('identificacion_oficial', 'Identificación Oficial'), ('poliza_seguro', 'Póliza de Seguro')], max_length=50)),
                ('documento', models.FileField(upload_to='documentos/conductores/')),
                ('necesita_autorizacion', models.BooleanField(default=True)),
                ('autorizado', models.BooleanField(default=False)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarioconductor')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPasajero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('solicito_conductor', models.BooleanField(default=False)),
                ('aprobado_pasajero', models.BooleanField(default=False)),
                ('aprobado_conductor', models.BooleanField(default=False)),
                ('fecha_aprobado_pasajero', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobado_conductor', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('conductor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarioconductor')),
                ('pasajero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariopasajero')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentacionPasajero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('credencial_universitaria', 'Credencial Universitaria'), ('boleta_rectoria', 'Boleta de Rectoría')], max_length=50)),
                ('documento', models.FileField(upload_to='documentos/pasajeros/')),
                ('necesita_autorizacion', models.BooleanField(default=True)),
                ('autorizado', models.BooleanField(default=False)),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariopasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=255)),
                ('es_hacia_fime', models.BooleanField()),
                ('hora_salida', models.CharField(max_length=10)),
                ('hora_llegada', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('asientos_disponibles', models.PositiveIntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_viaje', models.DateField()),
                ('fecha_ofrecido', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='usuarios.usuarioconductor')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asignado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarios.usuarioconductor')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarios.usuariopasajero')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarios.viaje')),
            ],
        ),
    ]
