# Generated by Django 5.1.7 on 2026-05-12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificacionIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleta_pagada', models.BooleanField(default=False)),
                ('matricula_en_boleta', models.BooleanField(default=False)),
                ('matricula_en_credencial', models.BooleanField(default=False)),
                ('matricula_coincide', models.BooleanField(default=False)),
                ('face_match_registro', models.BooleanField(default=False)),
                ('similitud_face_registro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('registro_aprobado', models.BooleanField(default=False)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('detalle_respuesta', models.JSONField(blank=True, default=dict)),
                ('fecha_verificacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verificacion_identidad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
