# Generated by Django 5.1.7 on 2026-04-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_mensaje"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="ai_face_present",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentacionpasajero",
            name="ai_face_similarity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentacionpasajero",
            name="ai_boleta_valid",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
